name: React CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JavaScript dependencies
        run: npm install

      - name: Run Frontend Tests
        run: npm run test

      - name: Build Frontend
        run: npm run build